// <auto-generated />
using System;
using System.Collections.Generic;
using CMMS.DAL.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CMMS.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517030320_ReplaceGatewayWithContract")]
    partial class ReplaceGatewayWithContract
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CMMS.DAL.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AttachmentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("attachment_type");

                    b.Property<string>("CloudinaryPublicId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cloudinary_public_id");

                    b.Property<string>("CloudinarySecureUrl")
                        .HasColumnType("text")
                        .HasColumnName("cloudinary_secure_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FileExtension")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("file_extension");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("object_id");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("object_type");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("attachment_pkey");

                    b.HasIndex("UploadedBy");

                    b.HasIndex("ObjectType", "ObjectId")
                        .HasDatabaseName("idx_attachment_object");

                    b.ToTable("attachment", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Bed", b =>
                {
                    b.Property<Guid>("BedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("bed_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("BedArea")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("bed_area");

                    b.Property<DateTime?>("BedCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("bed_created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<double?>("BedLength")
                        .HasColumnType("double precision")
                        .HasColumnName("bed_length");

                    b.Property<string>("BedName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bed_name");

                    b.Property<string>("BedStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bed_status");

                    b.Property<double?>("BedWidth")
                        .HasColumnType("double precision")
                        .HasColumnName("bed_width");

                    b.Property<int?>("CropQuantities")
                        .HasColumnType("integer")
                        .HasColumnName("crop_quantities");

                    b.Property<double?>("PathWidth")
                        .HasColumnType("double precision")
                        .HasColumnName("path_width");

                    b.Property<int?>("PlantCount")
                        .HasColumnType("integer")
                        .HasColumnName("plant_count");

                    b.Property<Guid?>("PlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("plot_id");

                    b.Property<int?>("RowCount")
                        .HasColumnType("integer")
                        .HasColumnName("row_count");

                    b.HasKey("BedId")
                        .HasName("beds_pkey");

                    b.HasIndex("PlotId");

                    b.ToTable("beds", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Crop", b =>
                {
                    b.Property<Guid>("CropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("crop_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double?>("BedWidthDefault")
                        .HasColumnType("double precision")
                        .HasColumnName("bed_width_default");

                    b.Property<int?>("CropDefaultGrowthDays")
                        .HasColumnType("integer")
                        .HasColumnName("crop_default_growth_days");

                    b.Property<string>("CropName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("crop_name");

                    b.Property<int?>("CropQuantities")
                        .HasColumnType("integer")
                        .HasColumnName("crop_quantities");

                    b.Property<string>("CropScientificName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("crop_scientific_name");

                    b.Property<string>("CropStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("crop_status");

                    b.Property<double?>("PathWidthDefault")
                        .HasColumnType("double precision")
                        .HasColumnName("path_width_default");

                    b.Property<double?>("PlantSpacing")
                        .HasColumnType("double precision")
                        .HasColumnName("plant_spacing");

                    b.Property<double?>("RowSpacing")
                        .HasColumnType("double precision")
                        .HasColumnName("row_spacing");

                    b.Property<int?>("RowsPerBed")
                        .HasColumnType("integer")
                        .HasColumnName("rows_per_bed");

                    b.HasKey("CropId")
                        .HasName("crops_pkey");

                    b.ToTable("crops", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.CropGrowthStage", b =>
                {
                    b.Property<Guid>("StageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("stage_id");

                    b.Property<string>("CommonDiseases")
                        .HasColumnType("text")
                        .HasColumnName("common_diseases");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CropId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_id");

                    b.Property<string>("GrowthIndicators")
                        .HasColumnType("text")
                        .HasColumnName("growth_indicators");

                    b.Property<double?>("HumidityMin")
                        .HasColumnType("double precision")
                        .HasColumnName("humidity_min");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<double?>("SoilMoistureMin")
                        .HasColumnType("double precision")
                        .HasColumnName("soil_moisture_min");

                    b.Property<string>("StageDescription")
                        .HasColumnType("text")
                        .HasColumnName("stage_description");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("stage_name");

                    b.Property<double?>("TemperatureMin")
                        .HasColumnType("double precision")
                        .HasColumnName("temperature_min");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("StageId");

                    b.HasIndex("CropId");

                    b.ToTable("crop_growth_stages", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.CropGrowthTask", b =>
                {
                    b.Property<Guid>("GrowthTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("growth_task_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("Frequency")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("frequency");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean")
                        .HasColumnName("is_mandatory");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<double?>("QuantityPerUnit")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity_per_unit");

                    b.Property<string>("QuantityUnit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("quantity_unit");

                    b.Property<string>("RequiredMaterials")
                        .HasColumnType("text")
                        .HasColumnName("required_materials");

                    b.Property<string>("RequiredTools")
                        .HasColumnType("text")
                        .HasColumnName("required_tools");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid")
                        .HasColumnName("stage_id");

                    b.Property<string>("TaskDescription")
                        .HasColumnType("text")
                        .HasColumnName("task_description");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("GrowthTaskId");

                    b.HasIndex("StageId");

                    b.HasIndex("TaskId");

                    b.ToTable("crop_growth_tasks", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.DiagnosisContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccountHolder")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("account_holder");

                    b.Property<string>("BankAccount")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bank_account");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bank_name");

                    b.Property<string>("ContractCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("contract_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("ExpertId")
                        .HasColumnType("uuid")
                        .HasColumnName("expert_id");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("PricePerDiagnosis")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("price_per_diagnosis");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("diagnosis_contract_pkey");

                    b.HasIndex("ContractCode")
                        .IsUnique()
                        .HasDatabaseName("diagnosis_contract_code_unique");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ExpertId");

                    b.HasIndex("FarmId", "ExpertId")
                        .HasDatabaseName("idx_contract_farm_expert");

                    b.ToTable("diagnosis_contract", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.DiagnosisPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("amount");

                    b.Property<string>("BillImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bill_image_url");

                    b.Property<string>("BillPublicId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bill_public_id");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("Month")
                        .HasColumnType("date")
                        .HasColumnName("month");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("paid_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<int>("TotalDiagnoses")
                        .HasColumnType("integer")
                        .HasColumnName("total_diagnoses");

                    b.HasKey("Id")
                        .HasName("diagnosis_payment_pkey");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_payment_status");

                    b.HasIndex("ContractId", "Month")
                        .IsUnique()
                        .HasDatabaseName("diagnosis_payment_contract_month_unique");

                    b.ToTable("diagnosis_payment", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.DiagnosisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Conclusion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conclusion");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DiagnosedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnosed_by");

                    b.Property<string>("DiseaseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("disease_name");

                    b.Property<string>("RecommendedAction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recommended_action");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<string>("SeverityLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity_level");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("diagnosis_result_pkey");

                    b.HasIndex("DiagnosedBy");

                    b.HasIndex("ReportId");

                    b.ToTable("diagnosis_result", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Farm", b =>
                {
                    b.Property<Guid>("FarmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("FarmArea")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("farm_area");

                    b.Property<DateTime?>("FarmCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("farm_created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FarmLocation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("farm_location");

                    b.Property<string>("FarmName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("farm_name");

                    b.Property<string>("FarmStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("farm_status");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("longitude");

                    b.HasKey("FarmId")
                        .HasName("farms_pkey");

                    b.ToTable("farms", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.GrowthTracking", b =>
                {
                    b.Property<Guid>("TrackingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tracking_id");

                    b.Property<double?>("ActualHeight")
                        .HasColumnType("double precision")
                        .HasColumnName("actual_height");

                    b.Property<double?>("ActualYield")
                        .HasColumnType("double precision")
                        .HasColumnName("actual_yield");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<int?>("DelayDays")
                        .HasColumnType("integer")
                        .HasColumnName("delay_days");

                    b.Property<string>("DelayReason")
                        .HasColumnType("text")
                        .HasColumnName("delay_reason");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("end_date");

                    b.Property<Guid>("HarvestDetailId")
                        .HasColumnType("uuid")
                        .HasColumnName("harvest_detail_id");

                    b.Property<string>("HealthStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("health_status");

                    b.Property<DateTime?>("LastObservedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_observed_at");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid")
                        .HasColumnName("stage_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("start_date");

                    b.Property<string>("TrackingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tracking_status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("TrackingId");

                    b.HasIndex("HarvestDetailId");

                    b.HasIndex("StageId");

                    b.ToTable("growth_tracking", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Harvest", b =>
                {
                    b.Property<Guid>("HarvestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("harvest_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CropId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_id");

                    b.Property<DateOnly?>("ExpectedDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_date");

                    b.Property<decimal?>("ExpectedQuantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("expected_quantity");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("PlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("plot_id");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("planned")
                        .HasColumnName("status");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("HarvestId")
                        .HasName("harvest_pkey");

                    b.HasIndex("CropId");

                    b.HasIndex("PlotId");

                    b.HasIndex("SeasonId");

                    b.ToTable("harvest", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.HarvestDetail", b =>
                {
                    b.Property<Guid>("HarvestDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("harvest_detail_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly?>("ActualHarvestDate")
                        .HasColumnType("date")
                        .HasColumnName("actual_harvest_date");

                    b.Property<int?>("ActualQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("actual_quantity");

                    b.Property<decimal?>("ActualWeightKg")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("actual_weight_kg");

                    b.Property<Guid?>("BedId")
                        .HasColumnType("uuid")
                        .HasColumnName("bed_id");

                    b.Property<int?>("CropQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("crop_quantity");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("HarvestId")
                        .HasColumnType("uuid")
                        .HasColumnName("harvest_id");

                    b.Property<string>("HarvestNotes")
                        .HasColumnType("text")
                        .HasColumnName("harvest_notes");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("HarvestDetailId")
                        .HasName("harvest_detail_pkey");

                    b.HasIndex("BedId");

                    b.HasIndex("HarvestId");

                    b.ToTable("harvest_detail", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.IotData", b =>
                {
                    b.Property<Guid>("SensorDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_data_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<double?>("Humidity")
                        .HasColumnType("double precision")
                        .HasColumnName("humidity");

                    b.Property<bool>("IsAlert")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_alert");

                    b.Property<bool?>("IsRaining")
                        .HasColumnType("boolean")
                        .HasColumnName("is_raining");

                    b.Property<double?>("Light")
                        .HasColumnType("double precision")
                        .HasColumnName("light");

                    b.Property<string>("RawData")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_data");

                    b.Property<DateTime?>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<double?>("SoilMoisture")
                        .HasColumnType("double precision")
                        .HasColumnName("soil_moisture");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision")
                        .HasColumnName("temperature");

                    b.HasKey("SensorDataId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("SeasonId");

                    b.ToTable("iot_data", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.IotDevice", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("ApiKeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("api_key_hash");

                    b.Property<DateTime?>("ApiKeyRotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("api_key_rotated_at");

                    b.Property<Guid?>("BedId")
                        .HasColumnType("uuid")
                        .HasColumnName("bed_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("device_code");

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("date")
                        .HasColumnName("installation_date");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("DeviceId");

                    b.HasIndex("ApiKeyHash")
                        .IsUnique();

                    b.HasIndex("BedId");

                    b.ToTable("iot_devices", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Notification", b =>
                {
                    b.Property<Guid>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("note_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("DiagnosisId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnosis_id");

                    b.Property<DateTime?>("NoteCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("note_created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("NoteMessage")
                        .HasColumnType("text")
                        .HasColumnName("note_message");

                    b.Property<string>("NoteStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("note_status");

                    b.Property<string>("NoteTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note_title");

                    b.Property<string>("NoteType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("note_type");

                    b.Property<Guid?>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("NoteId")
                        .HasName("notification_pkey");

                    b.HasIndex("DiagnosisId");

                    b.HasIndex("ReportId");

                    b.HasIndex("UserId");

                    b.ToTable("notification", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Plot", b =>
                {
                    b.Property<Guid>("PlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("plot_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<decimal?>("PlotArea")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("plot_area");

                    b.Property<DateTime?>("PlotCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("plot_created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<double?>("PlotLength")
                        .HasColumnType("double precision")
                        .HasColumnName("plot_length");

                    b.Property<double>("PlotMarginLength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(1.0)
                        .HasColumnName("plot_margin_length");

                    b.Property<double>("PlotMarginWidth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.29999999999999999)
                        .HasColumnName("plot_margin_width");

                    b.Property<string>("PlotName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("plot_name");

                    b.Property<string>("PlotStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plot_status");

                    b.Property<double?>("PlotWidth")
                        .HasColumnType("double precision")
                        .HasColumnName("plot_width");

                    b.Property<Guid?>("SoilId")
                        .HasColumnType("uuid")
                        .HasColumnName("soil_id");

                    b.HasKey("PlotId")
                        .HasName("plots_pkey");

                    b.HasIndex("FarmId");

                    b.HasIndex("SoilId");

                    b.ToTable("plots", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Recommendation", b =>
                {
                    b.Property<Guid>("RecommendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("DiagnosisId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnosis_id");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("RecommendationId")
                        .HasName("recommendation_pkey");

                    b.HasIndex("DiagnosisId");

                    b.HasIndex("SeasonId");

                    b.ToTable("recommendation", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.RecommendationTask", b =>
                {
                    b.Property<Guid>("RecommendationTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_task_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AssignedToWorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to_worker_id");

                    b.Property<Guid?>("CreatedByOwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_owner_id");

                    b.Property<DateTime?>("TaskCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("task_created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("TaskScheduledAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("task_scheduled_at");

                    b.Property<string>("TaskStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("task_status");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("RecommendationTaskId")
                        .HasName("recommendation_tasks_pkey");

                    b.HasIndex("AssignedToWorkerId");

                    b.HasIndex("CreatedByOwnerId");

                    b.ToTable("recommendation_tasks", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Report", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("report_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AiResultsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("ai_results_json");

                    b.Property<Guid?>("BedId")
                        .HasColumnType("uuid")
                        .HasColumnName("bed_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("PlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("plot_id");

                    b.Property<string>("ReportNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("report_no");

                    b.Property<string>("ReportType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("report_type");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmitDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("submit_date");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("ReportId")
                        .HasName("report_pkey");

                    b.HasIndex("BedId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PlotId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("WorkerId");

                    b.ToTable("report", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.ReportAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<Guid>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("report_assignment_pkey");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("ReportId");

                    b.ToTable("report_assignment", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.ReportEnvironmentSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<double?>("Humidity")
                        .HasColumnType("double precision")
                        .HasColumnName("humidity");

                    b.Property<double?>("LightIntensity")
                        .HasColumnType("double precision")
                        .HasColumnName("light_intensity");

                    b.Property<double?>("Rainfall")
                        .HasColumnType("double precision")
                        .HasColumnName("rainfall");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<double?>("SoilMoisture")
                        .HasColumnType("double precision")
                        .HasColumnName("soil_moisture");

                    b.Property<Guid?>("SourceDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_device_id");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision")
                        .HasColumnName("temperature");

                    b.HasKey("Id")
                        .HasName("report_environment_snapshot_pkey");

                    b.HasIndex("ReportId");

                    b.HasIndex("SourceDeviceId");

                    b.ToTable("report_environment_snapshot", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("role_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("role_pkey");

                    b.ToTable("role", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Season", b =>
                {
                    b.Property<Guid>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("season_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<DateTime?>("SeasonCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("season_created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("SeasonEndDate")
                        .HasColumnType("date")
                        .HasColumnName("season_end_date");

                    b.Property<string>("SeasonName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("season_name");

                    b.Property<string>("SeasonNotes")
                        .HasColumnType("text")
                        .HasColumnName("season_notes");

                    b.Property<DateOnly?>("SeasonStartDate")
                        .HasColumnType("date")
                        .HasColumnName("season_start_date");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("SeasonId")
                        .HasName("seasons_pkey");

                    b.HasIndex("FarmId");

                    b.ToTable("seasons", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Soil", b =>
                {
                    b.Property<Guid>("SoilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("soil_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ScienceName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("science_name");

                    b.HasKey("SoilId")
                        .HasName("soil_pkey");

                    b.ToTable("soil", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.SoilCropCompatibility", b =>
                {
                    b.Property<Guid>("ComptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("compt_id");

                    b.Property<string>("Compatibility")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("compatibility");

                    b.Property<Guid>("CropId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("SoilId")
                        .HasColumnType("uuid")
                        .HasColumnName("soil_id");

                    b.HasKey("ComptId");

                    b.HasIndex("CropId");

                    b.HasIndex("SoilId");

                    b.ToTable("soil_crop_compatibility", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Task", b =>
                {
                    b.Property<Guid>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("task_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("TaskCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("task_created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("TaskNotes")
                        .HasColumnType("text")
                        .HasColumnName("task_notes");

                    b.Property<DateTime?>("TaskScheduledAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("task_scheduled_at");

                    b.Property<string>("TaskStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("task_status");

                    b.Property<string>("TaskTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("task_title");

                    b.Property<string>("TaskType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("task_type");

                    b.HasKey("TaskId")
                        .HasName("tasks_pkey");

                    b.ToTable("tasks", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.TaskDetail", b =>
                {
                    b.Property<Guid>("TaskDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("task_detail_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<List<Guid>>("AssignedToWorkerIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("assigned_to_worker_ids");

                    b.Property<List<Guid>>("BedIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("bed_ids");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("end_date");

                    b.Property<Guid?>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<List<Guid>>("PlotIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("plot_ids");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("TaskDetailId")
                        .HasName("task_detail_pkey");

                    b.HasIndex("FarmId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TaskId");

                    b.ToTable("task_detail", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fullname");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RequestedRole")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("requested_role");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.WorkerSchedule", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("RecommendationTaskDetailTaskDetailId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TaskDetailId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_detail_id");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("ScheduleId")
                        .HasName("worker_schedule_pkey");

                    b.HasIndex("RecommendationTaskDetailTaskDetailId");

                    b.HasIndex("TaskDetailId");

                    b.HasIndex("WorkerId");

                    b.ToTable("worker_schedule", "public");
                });

            modelBuilder.Entity("RecommendationTaskDetail", b =>
                {
                    b.Property<Guid>("TaskDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("task_detail_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AssignedToWorkerIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("assigned_to_worker_ids");

                    b.Property<string>("BedIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("bed_ids");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("end_date");

                    b.Property<Guid?>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PlotIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("plot_ids");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("TaskDetailId")
                        .HasName("recommendation_task_detail_pkey");

                    b.HasIndex("FarmId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("recommendation_task_detail", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Attachment", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("attachment_uploaded_by_fkey");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Bed", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.Plot", "Plot")
                        .WithMany("Beds")
                        .HasForeignKey("PlotId")
                        .HasConstraintName("beds_plot_id_fkey");

                    b.Navigation("Plot");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.CropGrowthStage", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.Crop", "Crop")
                        .WithMany("CropGrowthStages")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("crop_growth_stages_crop_id_fkey");

                    b.Navigation("Crop");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.CropGrowthTask", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.CropGrowthStage", "CropGrowthStage")
                        .WithMany("CropGrowthTasks")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("crop_growth_tasks_stage_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.Task", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .HasConstraintName("crop_growth_tasks_task_id_fkey");

                    b.Navigation("CropGrowthStage");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.DiagnosisContract", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("diagnosis_contract_created_by_fkey");

                    b.HasOne("CMMS.DAL.Entities.User", "Expert")
                        .WithMany()
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("diagnosis_contract_expert_fkey");

                    b.HasOne("CMMS.DAL.Entities.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("diagnosis_contract_farm_fkey");

                    b.Navigation("Creator");

                    b.Navigation("Expert");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.DiagnosisPayment", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.DiagnosisContract", "Contract")
                        .WithMany("Payments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("diagnosis_payment_contract_fkey");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.DiagnosisResult", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.User", "Diagnoser")
                        .WithMany()
                        .HasForeignKey("DiagnosedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("diagnosis_result_diagnosed_by_fkey");

                    b.HasOne("CMMS.DAL.Entities.Report", "Report")
                        .WithMany("DiagnosisResults")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("diagnosis_result_report_id_fkey");

                    b.Navigation("Diagnoser");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.GrowthTracking", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.HarvestDetail", "HarvestDetail")
                        .WithMany("GrowthTrackings")
                        .HasForeignKey("HarvestDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("growth_tracking_harvest_detail_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.CropGrowthStage", "CropGrowthStage")
                        .WithMany("GrowthTrackings")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("growth_tracking_stage_id_fkey");

                    b.Navigation("CropGrowthStage");

                    b.Navigation("HarvestDetail");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Harvest", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.Crop", "Crop")
                        .WithMany("Harvests")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("harvest_crop_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.Plot", "Plot")
                        .WithMany("Harvests")
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("harvest_plot_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.Season", "Season")
                        .WithMany("Harvests")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("harvest_season_id_fkey");

                    b.Navigation("Crop");

                    b.Navigation("Plot");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.HarvestDetail", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.Bed", "Bed")
                        .WithMany("HarvestDetails")
                        .HasForeignKey("BedId")
                        .HasConstraintName("harvest_detail_bed_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.Harvest", "Harvest")
                        .WithMany("HarvestDetails")
                        .HasForeignKey("HarvestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("harvest_detail_harvest_id_fkey");

                    b.Navigation("Bed");

                    b.Navigation("Harvest");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.IotData", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.IotDevice", "Device")
                        .WithMany("IotDatas")
                        .HasForeignKey("DeviceId")
                        .HasConstraintName("fk_iot_data_iot_devices");

                    b.HasOne("CMMS.DAL.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .HasConstraintName("fk_iot_data_seasons");

                    b.Navigation("Device");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.IotDevice", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.Bed", "Bed")
                        .WithMany("IotDevices")
                        .HasForeignKey("BedId")
                        .HasConstraintName("fk_iot_devices_beds");

                    b.Navigation("Bed");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Notification", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.DiagnosisResult", "Diagnosis")
                        .WithMany()
                        .HasForeignKey("DiagnosisId")
                        .HasConstraintName("notification_diagnosis_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.Report", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .HasConstraintName("notification_report_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("notification_user_id_fkey");

                    b.Navigation("Diagnosis");

                    b.Navigation("Report");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Plot", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.Farm", "Farm")
                        .WithMany("Plots")
                        .HasForeignKey("FarmId")
                        .HasConstraintName("plots_farm_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.Soil", "Soil")
                        .WithMany("Plots")
                        .HasForeignKey("SoilId")
                        .HasConstraintName("plots_soil_id_fkey");

                    b.Navigation("Farm");

                    b.Navigation("Soil");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Recommendation", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.DiagnosisResult", "Diagnosis")
                        .WithMany("Recommendations")
                        .HasForeignKey("DiagnosisId")
                        .HasConstraintName("recommendation_diagnosis_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.Season", "Season")
                        .WithMany("Recommendations")
                        .HasForeignKey("SeasonId")
                        .HasConstraintName("recommendation_season_id_fkey");

                    b.Navigation("Diagnosis");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.RecommendationTask", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.User", "AssignedToWorker")
                        .WithMany("RecommendationTaskAssignedToWorkers")
                        .HasForeignKey("AssignedToWorkerId")
                        .HasConstraintName("recommendation_tasks_assigned_to_worker_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.User", "CreatedByOwner")
                        .WithMany("RecommendationTaskCreatedByOwners")
                        .HasForeignKey("CreatedByOwnerId")
                        .HasConstraintName("recommendation_tasks_created_by_owner_id_fkey");

                    b.Navigation("AssignedToWorker");

                    b.Navigation("CreatedByOwner");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Report", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.Bed", "Bed")
                        .WithMany()
                        .HasForeignKey("BedId")
                        .HasConstraintName("report_bed_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.User", "Owner")
                        .WithMany("OwnedReports")
                        .HasForeignKey("OwnerId")
                        .HasConstraintName("report_owner_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.Plot", "Plot")
                        .WithMany()
                        .HasForeignKey("PlotId")
                        .HasConstraintName("report_plot_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .HasConstraintName("report_season_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.User", "Worker")
                        .WithMany("WorkerReports")
                        .HasForeignKey("WorkerId")
                        .HasConstraintName("report_worker_id_fkey");

                    b.Navigation("Bed");

                    b.Navigation("Owner");

                    b.Navigation("Plot");

                    b.Navigation("Season");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.ReportAssignment", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.User", "Assigner")
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("report_assignment_assigned_by_fkey");

                    b.HasOne("CMMS.DAL.Entities.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("report_assignment_assigned_to_fkey");

                    b.HasOne("CMMS.DAL.Entities.Report", "Report")
                        .WithMany("ReportAssignments")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("report_assignment_report_id_fkey");

                    b.Navigation("Assignee");

                    b.Navigation("Assigner");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.ReportEnvironmentSnapshot", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.Report", "Report")
                        .WithMany("EnvironmentSnapshots")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("report_env_snapshot_report_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.IotDevice", "SourceDevice")
                        .WithMany()
                        .HasForeignKey("SourceDeviceId")
                        .HasConstraintName("report_env_snapshot_device_id_fkey");

                    b.Navigation("Report");

                    b.Navigation("SourceDevice");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Season", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.Farm", "Farm")
                        .WithMany("Seasons")
                        .HasForeignKey("FarmId")
                        .HasConstraintName("seasons_farm_id_fkey");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.SoilCropCompatibility", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.Crop", "Crop")
                        .WithMany("SoilCropCompatibilities")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("soil_crop_compatibility_crop_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.Soil", "Soil")
                        .WithMany("SoilCropCompatibilities")
                        .HasForeignKey("SoilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("soil_crop_compatibility_soil_id_fkey");

                    b.Navigation("Crop");

                    b.Navigation("Soil");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.TaskDetail", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.Farm", "Farm")
                        .WithMany("TaskDetails")
                        .HasForeignKey("FarmId");

                    b.HasOne("CMMS.DAL.Entities.Season", "Season")
                        .WithMany("TaskDetails")
                        .HasForeignKey("SeasonId")
                        .HasConstraintName("task_detail_season_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.Task", "Task")
                        .WithMany("TaskDetails")
                        .HasForeignKey("TaskId")
                        .HasConstraintName("task_detail_task_id_fkey");

                    b.Navigation("Farm");

                    b.Navigation("Season");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.User", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("users_role_id_fkey");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.WorkerSchedule", b =>
                {
                    b.HasOne("RecommendationTaskDetail", null)
                        .WithMany("WorkerSchedules")
                        .HasForeignKey("RecommendationTaskDetailTaskDetailId");

                    b.HasOne("CMMS.DAL.Entities.TaskDetail", "TaskDetail")
                        .WithMany("WorkerSchedules")
                        .HasForeignKey("TaskDetailId")
                        .HasConstraintName("worker_schedule_task_detail_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.User", "Worker")
                        .WithMany("WorkerSchedules")
                        .HasForeignKey("WorkerId")
                        .HasConstraintName("worker_schedule_worker_id_fkey");

                    b.Navigation("TaskDetail");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("RecommendationTaskDetail", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId");

                    b.HasOne("CMMS.DAL.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId");

                    b.HasOne("CMMS.DAL.Entities.RecommendationTask", "Task")
                        .WithMany("RecommendationTaskDetails")
                        .HasForeignKey("TaskId")
                        .HasConstraintName("recommendation_task_detail_task_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.User", null)
                        .WithMany("RecommendationTaskDetails")
                        .HasForeignKey("UserId");

                    b.Navigation("Farm");

                    b.Navigation("Season");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Bed", b =>
                {
                    b.Navigation("HarvestDetails");

                    b.Navigation("IotDevices");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Crop", b =>
                {
                    b.Navigation("CropGrowthStages");

                    b.Navigation("Harvests");

                    b.Navigation("SoilCropCompatibilities");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.CropGrowthStage", b =>
                {
                    b.Navigation("CropGrowthTasks");

                    b.Navigation("GrowthTrackings");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.DiagnosisContract", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.DiagnosisResult", b =>
                {
                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Farm", b =>
                {
                    b.Navigation("Plots");

                    b.Navigation("Seasons");

                    b.Navigation("TaskDetails");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Harvest", b =>
                {
                    b.Navigation("HarvestDetails");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.HarvestDetail", b =>
                {
                    b.Navigation("GrowthTrackings");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.IotDevice", b =>
                {
                    b.Navigation("IotDatas");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Plot", b =>
                {
                    b.Navigation("Beds");

                    b.Navigation("Harvests");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.RecommendationTask", b =>
                {
                    b.Navigation("RecommendationTaskDetails");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Report", b =>
                {
                    b.Navigation("DiagnosisResults");

                    b.Navigation("EnvironmentSnapshots");

                    b.Navigation("ReportAssignments");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Season", b =>
                {
                    b.Navigation("Harvests");

                    b.Navigation("Recommendations");

                    b.Navigation("TaskDetails");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Soil", b =>
                {
                    b.Navigation("Plots");

                    b.Navigation("SoilCropCompatibilities");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Task", b =>
                {
                    b.Navigation("TaskDetails");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.TaskDetail", b =>
                {
                    b.Navigation("WorkerSchedules");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("OwnedReports");

                    b.Navigation("RecommendationTaskAssignedToWorkers");

                    b.Navigation("RecommendationTaskCreatedByOwners");

                    b.Navigation("RecommendationTaskDetails");

                    b.Navigation("WorkerReports");

                    b.Navigation("WorkerSchedules");
                });

            modelBuilder.Entity("RecommendationTaskDetail", b =>
                {
                    b.Navigation("WorkerSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
