// <auto-generated />
using System;
using CMMS.DAL.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CMMS.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324032241_AddBedIdToTaskDetail")]
    partial class AddBedIdToTaskDetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CMMS.DAL.Entities.Bed", b =>
                {
                    b.Property<Guid>("BedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("bed_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("BedArea")
                        .HasColumnType("numeric")
                        .HasColumnName("bed_area");

                    b.Property<DateTime?>("BedCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bed_created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("BedName")
                        .HasColumnType("text")
                        .HasColumnName("bed_name");

                    b.Property<string>("BedStatus")
                        .HasColumnType("text")
                        .HasColumnName("bed_status");

                    b.Property<int?>("CropQuantities")
                        .HasColumnType("integer")
                        .HasColumnName("crop_quantities");

                    b.Property<Guid?>("PlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("plot_id");

                    b.HasKey("BedId")
                        .HasName("beds_pkey");

                    b.HasIndex("PlotId");

                    b.ToTable("beds", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Crop", b =>
                {
                    b.Property<Guid>("CropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("crop_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("CropDefaultGrowthDays")
                        .HasColumnType("integer")
                        .HasColumnName("crop_default_growth_days");

                    b.Property<string>("CropName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("crop_name");

                    b.Property<int?>("CropQuantities")
                        .HasColumnType("integer")
                        .HasColumnName("crop_quantities");

                    b.Property<string>("CropScientificName")
                        .HasColumnType("text")
                        .HasColumnName("crop_scientific_name");

                    b.Property<string>("CropStatus")
                        .HasColumnType("text")
                        .HasColumnName("crop_status");

                    b.Property<double?>("PlantSpacing")
                        .HasColumnType("double precision")
                        .HasColumnName("plant_spacing");

                    b.Property<Guid?>("SoilId")
                        .HasColumnType("uuid")
                        .HasColumnName("soil_id");

                    b.HasKey("CropId")
                        .HasName("crops_pkey");

                    b.HasIndex("SoilId");

                    b.ToTable("crops", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Farm", b =>
                {
                    b.Property<Guid>("FarmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("FarmArea")
                        .HasColumnType("numeric")
                        .HasColumnName("farm_area");

                    b.Property<DateTime?>("FarmCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("farm_created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FarmLocation")
                        .HasColumnType("text")
                        .HasColumnName("farm_location");

                    b.Property<string>("FarmName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("farm_name");

                    b.Property<string>("FarmStatus")
                        .HasColumnType("text")
                        .HasColumnName("farm_status");

                    b.HasKey("FarmId")
                        .HasName("farms_pkey");

                    b.ToTable("farms", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.ImageAnalysis", b =>
                {
                    b.Property<Guid>("ImageAnalysisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("image_analysis_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("AiLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("ai_latency_ms");

                    b.Property<string>("AiModel")
                        .HasColumnType("text")
                        .HasColumnName("ai_model");

                    b.Property<string>("AiModelVersion")
                        .HasColumnType("text")
                        .HasColumnName("ai_model_version");

                    b.Property<string>("AiPrompt")
                        .HasColumnType("text")
                        .HasColumnName("ai_prompt");

                    b.Property<string>("AiProvider")
                        .HasColumnType("text")
                        .HasColumnName("ai_provider");

                    b.Property<string>("AiRawResponseJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("ai_raw_response_json");

                    b.Property<string>("AiRequestId")
                        .HasColumnType("text")
                        .HasColumnName("ai_request_id");

                    b.Property<int?>("AiTokens")
                        .HasColumnType("integer")
                        .HasColumnName("ai_tokens");

                    b.Property<string>("AnalysisStatus")
                        .HasColumnType("text")
                        .HasColumnName("analysis_status");

                    b.Property<string>("AnalysisType")
                        .HasColumnType("text")
                        .HasColumnName("analysis_type");

                    b.Property<Guid?>("PhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_id");

                    b.HasKey("ImageAnalysisId")
                        .HasName("image_analyses_pkey");

                    b.HasIndex("PhotoId");

                    b.ToTable("image_analyses", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.ImageAnalysisResult", b =>
                {
                    b.Property<Guid>("ImageAnalysisResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("image_analysis_result_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("AiConfidence")
                        .HasColumnType("numeric")
                        .HasColumnName("ai_confidence");

                    b.Property<string>("AiLabel")
                        .HasColumnType("text")
                        .HasColumnName("ai_label");

                    b.Property<string>("AiSeverity")
                        .HasColumnType("text")
                        .HasColumnName("ai_severity");

                    b.Property<string>("BoundingBoxJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("bounding_box_json");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ExtraDataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("extra_data_json");

                    b.Property<Guid?>("ImageAnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_analysis_id");

                    b.HasKey("ImageAnalysisResultId")
                        .HasName("image_analysis_result_pkey");

                    b.HasIndex("ImageAnalysisId");

                    b.ToTable("image_analysis_result", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.IotData", b =>
                {
                    b.Property<Guid>("SensorDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_data_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<bool?>("IsAlert")
                        .HasColumnType("boolean")
                        .HasColumnName("is_alert");

                    b.Property<double?>("Max")
                        .HasColumnType("double precision")
                        .HasColumnName("max");

                    b.Property<double?>("Min")
                        .HasColumnType("double precision")
                        .HasColumnName("min");

                    b.Property<DateTime?>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<double?>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("SensorDataId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("SeasonId");

                    b.ToTable("iot_data", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.IotDevice", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<Guid?>("BedId")
                        .HasColumnType("uuid")
                        .HasColumnName("bed_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("date")
                        .HasColumnName("installation_date");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("DeviceId");

                    b.HasIndex("BedId");

                    b.ToTable("iot_devices", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Notification", b =>
                {
                    b.Property<Guid>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("note_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("NoteCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("note_created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("NoteMessage")
                        .HasColumnType("text")
                        .HasColumnName("note_message");

                    b.Property<string>("NoteStatus")
                        .HasColumnType("text")
                        .HasColumnName("note_status");

                    b.Property<string>("NoteTitle")
                        .HasColumnType("text")
                        .HasColumnName("note_title");

                    b.Property<string>("NoteType")
                        .HasColumnType("text")
                        .HasColumnName("note_type");

                    b.Property<Guid?>("PestDetectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("pest_detection_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("NoteId")
                        .HasName("notification_pkey");

                    b.HasIndex("PestDetectionId");

                    b.HasIndex("UserId");

                    b.ToTable("notification", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.PestDetection", b =>
                {
                    b.Property<Guid>("PestDetectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("pest_detection_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ConfidenceSource")
                        .HasColumnType("text")
                        .HasColumnName("confidence_source");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("DetectionStatus")
                        .HasColumnType("text")
                        .HasColumnName("detection_status");

                    b.Property<string>("GeneralLabel")
                        .HasColumnType("text")
                        .HasColumnName("general_label");

                    b.Property<string>("GeneralSeverity")
                        .HasColumnType("text")
                        .HasColumnName("general_severity");

                    b.Property<Guid?>("ImageAnalysisResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_analysis_result_id");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("text")
                        .HasColumnName("review_notes");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<Guid?>("SpecialistId")
                        .HasColumnType("uuid")
                        .HasColumnName("specialist_id");

                    b.HasKey("PestDetectionId")
                        .HasName("pest_detections_pkey");

                    b.HasIndex("ImageAnalysisResultId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("SpecialistId");

                    b.ToTable("pest_detections", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Photo", b =>
                {
                    b.Property<Guid>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("photo_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("HumidityAtTheMomentTakePhoto")
                        .HasColumnType("numeric")
                        .HasColumnName("humidity_at_the_moment_take_photo");

                    b.Property<DateOnly?>("PhotoDate")
                        .HasColumnType("date")
                        .HasColumnName("photo_date");

                    b.Property<string>("PhotoSource")
                        .HasColumnType("text")
                        .HasColumnName("photo_source");

                    b.Property<TimeOnly?>("PhotoTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("photo_time");

                    b.Property<decimal?>("RainfallAtTheMomentTakePhoto")
                        .HasColumnType("numeric")
                        .HasColumnName("rainfall_at_the_moment_take_photo");

                    b.Property<Guid?>("SeasonDetailId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_detail_id");

                    b.Property<decimal?>("SoilMoistureAtTheMomentTakePhoto")
                        .HasColumnType("numeric")
                        .HasColumnName("soil_moisture_at_the_moment_take_photo");

                    b.Property<decimal?>("TemperatureAtTheMomentTakePhoto")
                        .HasColumnType("numeric")
                        .HasColumnName("temperature_at_the_moment_take_photo");

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PhotoId")
                        .HasName("photo_pkey");

                    b.HasIndex("SeasonDetailId");

                    b.ToTable("photo", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Plot", b =>
                {
                    b.Property<Guid>("PlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("plot_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("BedCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bed_created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<decimal?>("PlotArea")
                        .HasColumnType("numeric")
                        .HasColumnName("plot_area");

                    b.Property<string>("PlotName")
                        .HasColumnType("text")
                        .HasColumnName("plot_name");

                    b.Property<string>("PlotStatus")
                        .HasColumnType("text")
                        .HasColumnName("plot_status");

                    b.Property<Guid?>("SoilId")
                        .HasColumnType("uuid")
                        .HasColumnName("soil_id");

                    b.HasKey("PlotId")
                        .HasName("plots_pkey");

                    b.HasIndex("FarmId");

                    b.HasIndex("SoilId");

                    b.ToTable("plots", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Recommendation", b =>
                {
                    b.Property<Guid>("RecommendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("PestDetectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("pest_detection_id");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("RecommendationId")
                        .HasName("recommendation_pkey");

                    b.HasIndex("PestDetectionId");

                    b.HasIndex("SeasonId");

                    b.ToTable("recommendation", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.RecommendationTask", b =>
                {
                    b.Property<Guid>("RecommendationTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_task_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AssignedToWorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to_worker_id");

                    b.Property<Guid?>("CreatedByOwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_owner_id");

                    b.Property<DateTime?>("TaskCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("task_created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("TaskScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("task_scheduled_at");

                    b.Property<string>("TaskStatus")
                        .HasColumnType("text")
                        .HasColumnName("task_status");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("RecommendationTaskId")
                        .HasName("recommendation_tasks_pkey");

                    b.HasIndex("AssignedToWorkerId");

                    b.HasIndex("CreatedByOwnerId");

                    b.ToTable("recommendation_tasks", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.RecommendationTaskDetail", b =>
                {
                    b.Property<Guid>("TaskDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("task_detail_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("TaskDetailId")
                        .HasName("recommendation_task_detail_pkey");

                    b.HasIndex("TaskId");

                    b.HasIndex("WorkerId");

                    b.ToTable("recommendation_task_detail", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Report", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("report_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmitDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submit_date");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("ReportId")
                        .HasName("report_pkey");

                    b.HasIndex("WorkerId");

                    b.ToTable("report", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("role_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("role_pkey");

                    b.ToTable("role", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Season", b =>
                {
                    b.Property<Guid>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("season_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<DateTime?>("SeasonCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("season_created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("SeasonEndDate")
                        .HasColumnType("date")
                        .HasColumnName("season_end_date");

                    b.Property<string>("SeasonName")
                        .HasColumnType("text")
                        .HasColumnName("season_name");

                    b.Property<string>("SeasonNotes")
                        .HasColumnType("text")
                        .HasColumnName("season_notes");

                    b.Property<DateOnly?>("SeasonStartDate")
                        .HasColumnType("date")
                        .HasColumnName("season_start_date");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("SeasonId")
                        .HasName("seasons_pkey");

                    b.HasIndex("FarmId");

                    b.ToTable("seasons", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.SeasonsDetail", b =>
                {
                    b.Property<Guid>("SeasonDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("season_detail_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BedId")
                        .HasColumnType("uuid")
                        .HasColumnName("bed_id");

                    b.Property<Guid?>("CropId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_id");

                    b.Property<int?>("CropQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("crop_quantity");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateOnly?>("SeasonExpectedHarvestDate")
                        .HasColumnType("date")
                        .HasColumnName("season_expected_harvest_date");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<decimal?>("TotalHarvestYield")
                        .HasColumnType("numeric")
                        .HasColumnName("total_harvest_yield");

                    b.HasKey("SeasonDetailId")
                        .HasName("seasons_detail_pkey");

                    b.HasIndex("BedId");

                    b.HasIndex("CropId");

                    b.HasIndex("SeasonId");

                    b.ToTable("seasons_detail", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Soil", b =>
                {
                    b.Property<Guid>("SoilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("soil_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ScienceName")
                        .HasColumnType("text")
                        .HasColumnName("science_name");

                    b.HasKey("SoilId")
                        .HasName("soil_pkey");

                    b.ToTable("soil", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Task", b =>
                {
                    b.Property<Guid>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("task_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("TaskCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("task_created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("TaskNotes")
                        .HasColumnType("text")
                        .HasColumnName("task_notes");

                    b.Property<DateTime?>("TaskScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("task_scheduled_at");

                    b.Property<string>("TaskStatus")
                        .HasColumnType("text")
                        .HasColumnName("task_status");

                    b.Property<string>("TaskTitle")
                        .HasColumnType("text")
                        .HasColumnName("task_title");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("TaskId")
                        .HasName("tasks_pkey");

                    b.HasIndex("SeasonId");

                    b.HasIndex("UserId");

                    b.ToTable("tasks", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.TaskDetail", b =>
                {
                    b.Property<Guid>("TaskDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("task_detail_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AssignedToWorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to_worker_id");

                    b.Property<Guid?>("BedId")
                        .HasColumnType("uuid")
                        .HasColumnName("bed_id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("TaskDetailId")
                        .HasName("task_detail_pkey");

                    b.HasIndex("AssignedToWorkerId");

                    b.HasIndex("BedId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TaskId");

                    b.ToTable("task_detail", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .HasColumnType("text")
                        .HasColumnName("fullname");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.WorkerSchedule", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("TaskDetailId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_detail_id");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("ScheduleId")
                        .HasName("worker_schedule_pkey");

                    b.HasIndex("TaskDetailId");

                    b.HasIndex("WorkerId");

                    b.ToTable("worker_schedule", "public");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Bed", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.Plot", "Plot")
                        .WithMany("Beds")
                        .HasForeignKey("PlotId")
                        .HasConstraintName("beds_plot_id_fkey");

                    b.Navigation("Plot");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Crop", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.Soil", "Soil")
                        .WithMany("Crops")
                        .HasForeignKey("SoilId")
                        .HasConstraintName("crops_soil_id_fkey");

                    b.Navigation("Soil");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.ImageAnalysis", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.Photo", "Photo")
                        .WithMany("ImageAnalyses")
                        .HasForeignKey("PhotoId")
                        .HasConstraintName("image_analyses_photo_id_fkey");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.ImageAnalysisResult", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.ImageAnalysis", "ImageAnalysis")
                        .WithMany("ImageAnalysisResults")
                        .HasForeignKey("ImageAnalysisId")
                        .HasConstraintName("image_analysis_result_image_analysis_id_fkey");

                    b.Navigation("ImageAnalysis");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.IotData", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.IotDevice", "Device")
                        .WithMany("IotDatas")
                        .HasForeignKey("DeviceId")
                        .HasConstraintName("fk_iot_data_iot_devices");

                    b.HasOne("CMMS.DAL.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .HasConstraintName("fk_iot_data_seasons");

                    b.Navigation("Device");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.IotDevice", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.Bed", "Bed")
                        .WithMany("IotDevices")
                        .HasForeignKey("BedId")
                        .HasConstraintName("fk_iot_devices_beds");

                    b.Navigation("Bed");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Notification", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.PestDetection", "PestDetection")
                        .WithMany("Notifications")
                        .HasForeignKey("PestDetectionId")
                        .HasConstraintName("notification_pest_detection_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("notification_user_id_fkey");

                    b.Navigation("PestDetection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.PestDetection", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.ImageAnalysisResult", "ImageAnalysisResult")
                        .WithMany("PestDetections")
                        .HasForeignKey("ImageAnalysisResultId")
                        .HasConstraintName("pest_detections_image_analysis_result_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.Season", "Season")
                        .WithMany("PestDetections")
                        .HasForeignKey("SeasonId")
                        .HasConstraintName("pest_detections_season_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.User", "Specialist")
                        .WithMany("PestDetections")
                        .HasForeignKey("SpecialistId")
                        .HasConstraintName("pest_detections_specialist_id_fkey");

                    b.Navigation("ImageAnalysisResult");

                    b.Navigation("Season");

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Photo", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.SeasonsDetail", "SeasonDetail")
                        .WithMany("Photos")
                        .HasForeignKey("SeasonDetailId")
                        .HasConstraintName("photo_season_detail_id_fkey");

                    b.Navigation("SeasonDetail");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Plot", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.Farm", "Farm")
                        .WithMany("Plots")
                        .HasForeignKey("FarmId")
                        .HasConstraintName("plots_farm_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.Soil", "Soil")
                        .WithMany("Plots")
                        .HasForeignKey("SoilId")
                        .HasConstraintName("plots_soil_id_fkey");

                    b.Navigation("Farm");

                    b.Navigation("Soil");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Recommendation", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.PestDetection", "PestDetection")
                        .WithMany("Recommendations")
                        .HasForeignKey("PestDetectionId")
                        .HasConstraintName("recommendation_pest_detection_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.Season", "Season")
                        .WithMany("Recommendations")
                        .HasForeignKey("SeasonId")
                        .HasConstraintName("recommendation_season_id_fkey");

                    b.Navigation("PestDetection");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.RecommendationTask", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.User", "AssignedToWorker")
                        .WithMany("RecommendationTaskAssignedToWorkers")
                        .HasForeignKey("AssignedToWorkerId")
                        .HasConstraintName("recommendation_tasks_assigned_to_worker_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.User", "CreatedByOwner")
                        .WithMany("RecommendationTaskCreatedByOwners")
                        .HasForeignKey("CreatedByOwnerId")
                        .HasConstraintName("recommendation_tasks_created_by_owner_id_fkey");

                    b.Navigation("AssignedToWorker");

                    b.Navigation("CreatedByOwner");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.RecommendationTaskDetail", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.RecommendationTask", "Task")
                        .WithMany("RecommendationTaskDetails")
                        .HasForeignKey("TaskId")
                        .HasConstraintName("recommendation_task_detail_task_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.User", "Worker")
                        .WithMany("RecommendationTaskDetails")
                        .HasForeignKey("WorkerId")
                        .HasConstraintName("recommendation_task_detail_worker_id_fkey");

                    b.Navigation("Task");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Report", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.User", "Worker")
                        .WithMany("Reports")
                        .HasForeignKey("WorkerId")
                        .HasConstraintName("report_worker_id_fkey");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Season", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.Farm", "Farm")
                        .WithMany("Seasons")
                        .HasForeignKey("FarmId")
                        .HasConstraintName("seasons_farm_id_fkey");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.SeasonsDetail", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.Bed", "Bed")
                        .WithMany("SeasonsDetails")
                        .HasForeignKey("BedId")
                        .HasConstraintName("seasons_detail_bed_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.Crop", "Crop")
                        .WithMany("SeasonsDetails")
                        .HasForeignKey("CropId")
                        .HasConstraintName("seasons_detail_crop_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.Season", "Season")
                        .WithMany("SeasonsDetails")
                        .HasForeignKey("SeasonId")
                        .HasConstraintName("seasons_detail_season_id_fkey");

                    b.Navigation("Bed");

                    b.Navigation("Crop");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Task", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.Season", null)
                        .WithMany("Tasks")
                        .HasForeignKey("SeasonId");

                    b.HasOne("CMMS.DAL.Entities.User", null)
                        .WithMany("Tasks")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.TaskDetail", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.User", "AssignedToWorker")
                        .WithMany("TaskDetails")
                        .HasForeignKey("AssignedToWorkerId")
                        .HasConstraintName("task_detail_assigned_to_worker_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.Bed", "Bed")
                        .WithMany()
                        .HasForeignKey("BedId")
                        .HasConstraintName("task_detail_bed_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.Season", "Season")
                        .WithMany("TaskDetails")
                        .HasForeignKey("SeasonId")
                        .HasConstraintName("task_detail_season_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.Task", "Task")
                        .WithMany("TaskDetails")
                        .HasForeignKey("TaskId")
                        .HasConstraintName("task_detail_task_id_fkey");

                    b.Navigation("AssignedToWorker");

                    b.Navigation("Bed");

                    b.Navigation("Season");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.User", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("users_role_id_fkey");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.WorkerSchedule", b =>
                {
                    b.HasOne("CMMS.DAL.Entities.TaskDetail", "TaskDetail")
                        .WithMany("WorkerSchedules")
                        .HasForeignKey("TaskDetailId")
                        .HasConstraintName("worker_schedule_task_detail_id_fkey");

                    b.HasOne("CMMS.DAL.Entities.User", "Worker")
                        .WithMany("WorkerSchedules")
                        .HasForeignKey("WorkerId")
                        .HasConstraintName("worker_schedule_worker_id_fkey");

                    b.Navigation("TaskDetail");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Bed", b =>
                {
                    b.Navigation("IotDevices");

                    b.Navigation("SeasonsDetails");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Crop", b =>
                {
                    b.Navigation("SeasonsDetails");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Farm", b =>
                {
                    b.Navigation("Plots");

                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.ImageAnalysis", b =>
                {
                    b.Navigation("ImageAnalysisResults");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.ImageAnalysisResult", b =>
                {
                    b.Navigation("PestDetections");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.IotDevice", b =>
                {
                    b.Navigation("IotDatas");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.PestDetection", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Photo", b =>
                {
                    b.Navigation("ImageAnalyses");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Plot", b =>
                {
                    b.Navigation("Beds");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.RecommendationTask", b =>
                {
                    b.Navigation("RecommendationTaskDetails");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Season", b =>
                {
                    b.Navigation("PestDetections");

                    b.Navigation("Recommendations");

                    b.Navigation("SeasonsDetails");

                    b.Navigation("TaskDetails");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.SeasonsDetail", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Soil", b =>
                {
                    b.Navigation("Crops");

                    b.Navigation("Plots");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.Task", b =>
                {
                    b.Navigation("TaskDetails");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.TaskDetail", b =>
                {
                    b.Navigation("WorkerSchedules");
                });

            modelBuilder.Entity("CMMS.DAL.Entities.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("PestDetections");

                    b.Navigation("RecommendationTaskAssignedToWorkers");

                    b.Navigation("RecommendationTaskCreatedByOwners");

                    b.Navigation("RecommendationTaskDetails");

                    b.Navigation("Reports");

                    b.Navigation("TaskDetails");

                    b.Navigation("Tasks");

                    b.Navigation("WorkerSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
